import { Octokit } from "octokit";

interface CreateMigrationPRParams {
  sql: string;
  filename: string;
  title: string;
  description: string;
}

interface MigrationPRResult {
  prUrl: string;
  prNumber: number;
  branch: string;
}

function getConfig() {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;

  if (!token || !owner || !repo) {
    throw new Error(
      "Missing required env vars: GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO"
    );
  }
  return { token, owner, repo };
}

export async function createMigrationPR(
  params: CreateMigrationPRParams
): Promise<MigrationPRResult> {
  const { token, owner, repo } = getConfig();
  const octokit = new Octokit({ auth: token });

  const baseBranch = "main";
  const branchName = `migration/${params.filename.replace(/\.sql$/, "").replace(/[^a-z0-9_-]/gi, "-")}`;

  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  const baseSha = ref.object.sha;

  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  const filePath = `supabase/migrations/${params.filename}`;

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: `chore(migration): ${params.title}`,
    content: Buffer.from(params.sql).toString("base64"),
    branch: branchName,
  });

  const prBody = [
    "## Migration",
    "",
    params.description,
    "",
    "### Generated SQL",
    "",
    "```sql",
    params.sql,
    "```",
    "",
    "---",
    "*This PR was auto-generated by the schema change request API.*",
  ].join("\n");

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `[Migration] ${params.title}`,
    body: prBody,
    head: branchName,
    base: baseBranch,
  });

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    branch: branchName,
  };
}
