import { PromptOption, PromptCategory } from "./types";

const colorOptions: PromptOption[] = [
  { id: 800, label: "ブラック", value: "black" },
  { id: 801, label: "ホワイト", value: "white" },
  { id: 802, label: "グレー", value: "grey" },
  { id: 803, label: "ベージュ", value: "beige" },
  { id: 804, label: "ブラウン", value: "brown" },
  { id: 805, label: "チョコレート", value: "chocolate" },
  { id: 806, label: "ゴールド", value: "gold" },
  { id: 807, label: "シルバー", value: "silver" },
  { id: 808, label: "レッド", value: "red" },
  { id: 809, label: "ピンク", value: "pink" },
  { id: 810, label: "オレンジ", value: "orange" },
  { id: 811, label: "イエロー", value: "yellow" },
  { id: 812, label: "ブロンド", value: "blonde" },
  { id: 813, label: "ブルー", value: "blue" },
  { id: 814, label: "グリーン", value: "green" },
  { id: 815, label: "パープル", value: "purple" },
  { id: 816, label: "バーガンディ", value: "burgundy" },
  { id: 817, label: "ワインレッド", value: "wine red" },
  { id: 818, label: "プラチナ", value: "platinum" },
  { id: 819, label: "アッシュ", value: "ash" },
  { id: 820, label: "キャラメル", value: "caramel" },
  { id: 821, label: "ビオレット", value: "violet" },
  { id: 822, label: "ネオンピンク", value: "neon pink" },
  { id: 823, label: "ネオングリーン", value: "neon green" },
  { id: 824, label: "ダークブロンド", value: "dark blonde" },
  { id: 825, label: "ダークブルー", value: "dark blue" },
  { id: 826, label: "ライトブロンド", value: "light blonde" },
  { id: 827, label: "ライトブルー", value: "light blue" },
  { id: 828, label: "ダークグリーン", value: "dark green" },
  { id: 829, label: "ライトグリーン", value: "light green" },
];

export const color: PromptCategory[] = [{ label: "色", tags: colorOptions }];
