import { PromptOption, PromptCategory } from "./types";

const oralPlay: PromptOption[] = [
  { id: 156, label: "フェラチオ", value: "fellatio" },
  { id: 157, label: "イラマチオ(イマラチオ)", value: "irrumatio" },
  { id: 158, label: "ディープスロート", value: "deepthroat" },
  { id: 159, label: "セルフフェラ", value: "autofellatio" },
  { id: 160, label: "玉舐め", value: "licking testicle" },
  { id: 161, label: "玉フェラ", value: "testicle sucking" },
  { id: 162, label: "フェラ事後", value: "after fellatio" },
  { id: 163, label: "お掃除フェラ", value: "cleanup fellatio" },
  { id: 164, label: "Wフェラ", value: "cooperative fellatio" },
  { id: 165, label: "マスクフェラ", value: "fellatio under mask" },
  { id: 166, label: "チンポにキス", value: "kissing penis" },
  { id: 167, label: "リバースフェラ", value: "reverse fellatio" },
  { id: 168, label: "疑似フェラ", value: "simulated fellatio" },
  { id: 169, label: "立ちフェラ", value: "standing fellatio" },
];

const pussyActions: PromptOption[] = [
  { id: 238, label: "潮吹き", value: "female ejaculation" },
  { id: 239, label: "手マン", value: "fingering" },
  { id: 240, label: "オナニー", value: "female masturbation" },
  { id: 241, label: "クリトリスを刺激する", value: "clitoris tweak" },
  { id: 242, label: "くぱぁ", value: "spread pussy" },
  { id: 243, label: "クリ拷問", value: "clitoris torture" },
];

const bondageActions: PromptOption[] = [
  { id: 500, label: "縛られた", value: "bound" },
  { id: 501, label: "息を切らしている", value: "panting" },
  { id: 502, label: "腕を縛られた", value: "arms tied" },
  { id: 503, label: "縛り、支配", value: "bdsm" },
  { id: 504, label: "緊縛", value: "bondage" },
  { id: 505, label: "緊縛用具", value: "bondage gear" },
  { id: 506, label: "拘束されている", value: "restrained" },
  { id: 507, label: "寄りかかる", value: "leaning" },
  { id: 508, label: "拘束具", value: "restraints" },
  { id: 509, label: "壁に寄りかかる", value: "against wall" },
  { id: 510, label: "リード", value: "leash" },
  { id: 511, label: "後ろに傾く", value: "leaning backward" },
  { id: 512, label: "リードを引く", value: "leash pull" },
  { id: 513, label: "猿轡（さるぐつわ）", value: "gag" },
  { id: 514, label: "猿轡をされている", value: "gagged" },
  { id: 515, label: "ボールギャグ", value: "ball gag" },
  { id: 516, label: "動物の口を覆う器具", value: "muzzle (object)" },
  { id: 517, label: "服を脱ぐ", value: "undressing" },
  { id: 518, label: "口輪をつけられた", value: "muzzled" },
  { id: 519, label: "服を持ち上げる", value: "clothing lift" },
  { id: 520, label: "縄", value: "rope" },
  { id: 521, label: "シャツをめくる", value: "shirt lift" },
  { id: 522, label: "縄による拘束", value: "rope bondage" },
  { id: 523, label: "めくれ上がったシャツ", value: "raised shirt" },
  { id: 524, label: "鎖", value: "chain" },
  { id: 525, label: "持ち上げられた服", value: "raised clothing" },
  { id: 526, label: "鎖でつながれた", value: "chained" },
  { id: 527, label: "持ち上げられたトップス", value: "raised topwear" },
  { id: 528, label: "手錠", value: "cuff (restraint)" },
  { id: 529, label: "服をどかす", value: "clothing aside" },
  { id: 530, label: "手錠 2", value: "handcuffs" },
  { id: 531, label: "服を引っ張る", value: "clothing pull" },
  { id: 532, label: "金属の手錠", value: "metal cuffs" },
  { id: 533, label: "下着を下げている", value: "bottomwear down" },
  { id: 534, label: "手を縛られた", value: "hands tied" },
  { id: 535, label: "下着を下げている 2", value: "underwear down" },
  { id: 536, label: "足枷", value: "shackles" },
  { id: 537, label: "下着をずらした", value: "underwear aside" },
  { id: 538, label: "足を縛られた", value: "legs tied" },
  { id: 539, label: "下着を引っ張る", value: "underwear pull" },
  { id: 540, label: "宙吊り", value: "suspension" },
  { id: 541, label: "パンツを下げている", value: "panties down" },
  { id: 542, label: "逆さま", value: "upside down" },
  { id: 543, label: "パンツをずらす", value: "panties aside" },
  { id: 544, label: "何かに押さえつけられた状態", value: "pinned" },
  { id: 545, label: "ズボンを下げている", value: "pants down" },
  { id: 546, label: "鞭", value: "whip" },
  { id: 547, label: "何かを口にくわえた状態", value: "object in mouth" },
];

const playCategory: PromptCategory[] = [
  { label: "フェラ", tags: oralPlay },
  { label: "まんこ", tags: pussyActions },
  { label: "緊縛", tags: bondageActions },
];

export const play: PromptCategory[] = [{ label: "プレイ", tags: playCategory }];
